force-app/main/default/objects/Context__c/Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <displayFormat>CX-{00000000}</displayFormat>
        <label>Context Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Context</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Context__c/fields/List_ID__c.field-meta.xml
<CustomField>
    <fullName>List_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>List ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UpsertContext.cls
// Class without sharing so that guest users can upsert the context record of the list
// This method can only update the record from the list parameters retrieved in with sharing context
// Ref: https://developer.salesforce.com/docs/atlas.en-us.communities_dev.meta/communities_dev/communities_dev_give_guest_users_access_to_update_records.htm
public without sharing class UpsertContext {
    public static void UpsertContext(Context__c context) {
        Upsert context List_ID__c;
    }
}