force-app/main/default/objects/Smart_List_Definition__mdt/Smart_List_Definition__mdt.object-meta.xml
<CustomObject>
    <label>Smart List Definition</label>
    <pluralLabel>Smart List Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Smart_List_Definition__mdt/fields/Data_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Source_Type__c</fullName>
    <label>Data Source Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex Data Source</fullName>
            </value>
            <value>
                <fullName>Files</fullName>
            </value>
            <value>
                <fullName>SOQL without Sharing</fullName>
            </value>
            <value>
                <fullName>SOQL with Sharing</fullName>
                <default>true</default>
                <label>SOQL with Sharing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SmartListListNamePicklist.cls
global with sharing class SmartListListNamePicklist extends VisualEditor.DynamicPickList {
    private static VisualEditor.DataRow defaultValue = new VisualEditor.DataRow('--None--', null);
    private static VisualEditor.DynamicPickListRows picklist;

    global override VisualEditor.DataRow getDefaultValue(){
        return defaultValue;
    }

    global override VisualEditor.DynamicPickListRows getValues() {
        if (picklist == null) {
            picklist = new VisualEditor.DynamicPickListRows();
            VisualEditor.DataRow defaultValue = defaultValue;
            picklist.addRow(defaultValue);
            for (Smart_List_Definition__mdt sld : [SELECT DeveloperName, Label FROM Smart_List_Definition__mdt WHERE Data_Source_Type__c != 'Files' ORDER BY Label]) {
                VisualEditor.DataRow value = new VisualEditor.DataRow(sld.Label, sld.DeveloperName);
                picklist.addRow(value);
            }
        }
        return picklist;
    }
}